### ISSUE TITLE
Invalid name error when npm install

### ISSUE THREAD

**Issue by lowply** [benbalter/copy-issue-link-bookmarklet#1]
Hi Ben,

I really like this bookmarklet, this is what I've been looking for!! Thank you for making it an OSS project 😄  I just wanted to try building it locally but I encountered an error below:

```
$ npm i
npm WARN Invalid name: "Copy issue link Bookmarklet"
npm WARN copy-issue-link-bookmarklet No description
npm WARN copy-issue-link-bookmarklet No repository field.
npm WARN copy-issue-link-bookmarklet No README data
npm WARN copy-issue-link-bookmarklet No license field.
```

The log level is Warning, but actually it didn't install dependencies:

```
$ npm list
/Users/lowply/.ghq/github.com/benbalter/copy-issue-link-bookmarklet
└── (empty)

npm ERR! error in /Users/lowply/.ghq/github.com/benbalter/copy-issue-link-bookmarklet: Invalid name: "Copy issue link Bookmarklet"

$ ls -l node_modules/
total 0
```

It looks like there's some rules for `name` field. Please see [package.json](https://docs.npmjs.com/files/package.json)

So I tried

```
  "name": "copy-issue-link-bookmarklet",
```

And it worked. Hope it helps 😄

**Comment by benbalter** [comment]
> And it worked. Hope it helps

@lowply mind submitting a PR with that proposed change? I'd love to update the package file for other consumers.

**Comment by lowply** [comment]
Sure thing! I'm happy to submit a PR 👍
